site_name: AWS Community Projects
site_description: AWS Community Projects
site_author: AWS Community Builders

theme:
  name: material
  logo: media/logo.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - tables
  - meta
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 

# plugins:
#   - git-revision-date
#   - search

# extra:
#   analytics:
#     provider: google
#     property: UA-XXXXXXXX-X

# nav:
#   - Overview:
#     - index.md